version: "3.8"
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - "./docker/mysql/data/db:/var/lib/mysql"
    environment:
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    restart: on-failure
    ports:
      - "3307:3306"
  app:
    build: ./
    expose:
      - "9000"
    container_name: app
    volumes:
      - ".:/var/www/html"

  nginx:
    build: ./docker/nginx
    ports:
      - "8080:80"
    container_name: nginx
    volumes:
      - ".:/var/www/html"
    depends_on:
      - app
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "8001:80"
