version: "3.8"
services:
  evntoo-mysql:
    image: mysql:8.0
    container_name: evntoo-mysql
    volumes:
      - "./mysql/data/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    restart: on-failure
    ports:
    - "3307:3306"
  app:
    build: ./
    expose:
      - "9000"
    container_name: app
    volumes:
      - "./app:/var/www/html"

  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    container_name: nginx
    volumes:
      - "./app:/var/www/html"
    depends_on:
      - app
  myadmin:
    image: phpmyadmin/phpmyadmin
    container_name: myadmin
    links:
      - evntoo-mysql
    environment:
      PMA_HOST: evntoo-mysql
      PMA_PASSWORD: 123456
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123456
    ports:
      - "8001:80"

